spring.application.name=server
auth.jwt.secret=${SERVER_JWT_SECRET}
storage.base-path=${STORAGE_BASE_PATH:../images}
db.path=${DB_PATH:/home/mpserver}
spring.datasource.url=jdbc:sqlite:${db.path}/gallery.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=40MB
spring.servlet.multipart.max-request-size=80MB
server.tomcat.max-swallow-size=80MB

owner.username=${OWNER_USERNAME:admin}
owner.password=${OWNER_PASSWORD:change-asap}

